- name: Install the Raspberry Pi kernel
  community.general.pacman:
    name:
      - linux-rpi
      - raspberrypi-firmware
    state: present
    # The "linux-rpi" package conflicts with the default kernel
    # Change the default answer from N to Y when a conflict happens
    # https://unix.stackexchange.com/a/584001
    extra_args: --ask 4
  become: true
  # The Raspberry Pi kernel is required to enable the PoE HAT on Arch Linux ARM
  when: ansible_distribution == 'Archlinux'

- name: Make sure the other type of PoE HAT is not enabled
  ansible.builtin.lineinfile:
    path: "{{ rpi_boot_config_file }}"
    line: "dtoverlay={{ 'rpi-poe-plus' if dtoverlay == 'rpi-poe' else 'rpi-poe' }}"
    state: absent
  become: true
  register: boot_config_modified_remove_dtoverlay

- name: Enable PoE HAT in {{ rpi_boot_config_file }}
  ansible.builtin.lineinfile:
    path: "{{ rpi_boot_config_file }}"
    create: true
    owner: root
    group: root
    mode: "755"
    line: dtoverlay={{ dtoverlay }}
    insertbefore: ^\[.*\]
    firstmatch: true
    state: present
  become: true
  register: boot_config_modified_add_dtoverlay

- name: Insert the PoE HAT fan curves
  ansible.builtin.blockinfile:
    path: "{{ rpi_boot_config_file }}"
    insertafter: dtoverlay={{ dtoverlay }}
    block: |
      dtparam=poe_fan_temp0=10000,poe_fan_temp0_hyst=1000
      dtparam=poe_fan_temp1=55000,poe_fan_temp1_hyst=5000
      dtparam=poe_fan_temp2=60000,poe_fan_temp2_hyst=5000
      dtparam=poe_fan_temp3=65000,poe_fan_temp3_hyst=5000
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    state: present
  become: true
  register: boot_config_modified_add_curves

- name: Remove all other fan curves (1)
  ansible.builtin.replace:
    path: "{{ rpi_boot_config_file }}"
    before: dtoverlay={{ dtoverlay }}
    regexp: ^dtparam=poe_fan_temp.*\n
    replace: ""
  become: true
  register: boot_config_modified_remove1

- name: Remove all other fan curves (2)
  ansible.builtin.replace:
    path: "{{ rpi_boot_config_file }}"
    after: "# END ANSIBLE MANAGED BLOCK"
    regexp: ^dtparam=poe_fan_temp.*\n
    replace: ""
  become: true
  register: boot_config_modified_remove2

- name: Reboot the machine
  ansible.builtin.reboot:
    msg: Reboot by Ansible because {{ rpi_boot_config_file }} was modified
    reboot_timeout: 300
  become: true
  when: >-
    reboot | default(True) and (
      boot_config_modified_remove_dtoverlay.changed or
      boot_config_modified_add_dtoverlay.changed or
      boot_config_modified_add_curves.changed or
      boot_config_modified_remove1.changed or
      boot_config_modified_remove2.changed
    )
