driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  # We need an Arch Linux image with Python 3 and the "linux-rpi" and "raspberrypi-firmware"
  # packages available in order to test the playbooks
  # - name: archlinux
  #   image: archlinux:latest
  - name: debian-bullseye
    image: geerlingguy/docker-debian11-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  - name: debian-buster
    image: geerlingguy/docker-debian10-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  - name: ubuntu-20.04
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    # cleanup: cleanup.yaml
    # create: create.yaml
    converge: converge.yaml
    # destroy: destroy.yaml
    # prepare: prepare.yaml
    # side_effect: side_effect.yaml
    verify: verify.yaml
scenario:
  name: poe-hat-plus
verifier:
  name: ansible
dependency:
  name: galaxy
  options:
    role-file: requirements.yaml
    requirements-file: requirements.yaml
