- name: Prepare
  hosts: all

  tasks:
    - name: Install a SSH server
      ansible.builtin.apt:
        name: openssh-server
        update_cache: true
        state: present
      when: ansible_distribution in ['Debian', 'Ubuntu']
